import type { AddressValue } from '@skyrent/identity-sdk';
import type { Drone } from '../types/drone';

export const DRONES: Drone[] = [
  {
    id: 'atlas',
    name: 'Atlas Pro',
    description: 'Cinema-grade stability for epic aerial shots.',
    category: 'filming',
    rangeMiles: 12,
    maxSpeedMph: 42,
    dailyPrice: 220,
    icon: 'AP',
  },
  {
    id: 'quasar',
    name: 'Quasar X',
    description: 'Long-range, high-speed drone for expansive terrain.',
    category: 'filming',
    rangeMiles: 18,
    maxSpeedMph: 54,
    dailyPrice: 290,
    icon: 'QX',
  },
  {
    id: 'hover',
    name: 'Hover Scout',
    description: 'Compact build, perfect for indoor or tight spaces.',
    category: 'filming',
    rangeMiles: 6,
    maxSpeedMph: 28,
    dailyPrice: 160,
    icon: 'HS',
  },
  {
    id: 'cinema-vista',
    name: 'Cinema Vista',
    description: 'Ultra-smooth tracking for high-end production shots.',
    category: 'filming',
    rangeMiles: 10,
    maxSpeedMph: 38,
    dailyPrice: 260,
    icon: 'CV',
  },
  {
    id: 'aero-stable',
    name: 'Aero Stable',
    description: 'Wind-resistant hover with precision gimbal control.',
    category: 'filming',
    rangeMiles: 15,
    maxSpeedMph: 44,
    dailyPrice: 310,
    icon: 'AS',
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Low-light optimized sensors for dusk and night shoots.',
    category: 'filming',
    rangeMiles: 9,
    maxSpeedMph: 32,
    dailyPrice: 240,
    icon: 'NO',
  },
  {
    id: 'cargo-hauler',
    name: 'Cargo Hauler',
    description: 'Heavy-lift platform for mid-size deliveries.',
    category: 'cargo',
    rangeMiles: 8,
    maxSpeedMph: 22,
    dailyPrice: 340,
    loadCapacityLbs: 35,
    icon: 'CH',
  },
  {
    id: 'freightliner',
    name: 'Freightliner Max',
    description: 'Long-range cargo drone with stabilized payload bay.',
    category: 'cargo',
    rangeMiles: 14,
    maxSpeedMph: 30,
    dailyPrice: 420,
    loadCapacityLbs: 60,
    icon: 'FM',
  },
  {
    id: 'lift-cruiser',
    name: 'Lift Cruiser',
    description: 'Balanced range and payload for regional deliveries.',
    category: 'cargo',
    rangeMiles: 12,
    maxSpeedMph: 26,
    dailyPrice: 380,
    loadCapacityLbs: 45,
    icon: 'LC',
  },
  {
    id: 'payload-pro',
    name: 'Payload Pro',
    description: 'Reinforced frame for heavier shipments.',
    category: 'cargo',
    rangeMiles: 9,
    maxSpeedMph: 24,
    dailyPrice: 360,
    loadCapacityLbs: 55,
    icon: 'PP',
  },
];

export const EMPTY_ADDRESS: AddressValue = {
  line1: '',
  line2: '',
  city: '',
  region: '',
  postalCode: '',
  country: 'US',
};
